openapi: 3.0.0
info:
  title: L5 OpenApi
  description: L5 Swagger OpenApi description
  version: 1.0.0
paths:
  /:
    get:
      description: Home page
      operationId: ba07f30af47fc58b59f1d978c7034d99
      responses:
        default:
          description: Welcome page
