version: "3.3"
services:
    nginx:
        container_name: qberry-nginx
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - php
        volumes:
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    php:
        container_name: qberry-php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - .:/var/www/html
    mysql:
        container_name: qberry-mysql
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./db:/var/lib/mysql
    redis:
        image: redis:alpine
        container_name: qberry-redis
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass o251298
        ports:
            - "6379:6379"
        volumes:
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    cron:
        container_name: qberry-cron
        build:
            context: .
            dockerfile: .docker/cron/Dockerfile
        volumes:
            - .:/var/www/html
            - ./log/cron:/var/log/cron
        restart: always
